### PR TITLE
Fixed missing negate operator for option adding

### PR DESCRIPTION
**Pull request by Geolim4**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?   | no
| Fixed issue | #... 

Fixed missing negate operator for option adding which is not working actually.

### CODE REVIEW

**Comment by Geolim4** [comment]
@oallain @TheGrimmChester can you take a look at this PR which is a bit blocking ?
Thanks you very much.

**Review by TheGrimmChester — APPROVED** [review]
Thanks, the fix should be deployed soon when we will merge this PR or https://github.com/synolia/SyliusAkeneoPlugin/pull/73/files#diff-2a0a2b6830e1956ad7d667f0dd94c57fed8edcd95d28578f77756a6f3258c7a3R276

**Review by oallain — APPROVED** [review]

**Comment by oallain** [comment]
Thanks @Geolim4 :rocket:

**Comment by oallain** [comment]
New tag created [v2.2.2](https://github.com/synolia/SyliusAkeneoPlugin/releases/tag/v2.2.2)

**Pull request merged**
